### ISSUE TITLE
想询问一下有关模型的问题

### ISSUE THREAD

**Issue by freedomlyle** [Sg4Dylan/EfficientIR#1]
首先称赞一下这个项目，做得非常出色，对我这种刚转向研究ai特征匹配搜索的新手非常有帮助。
我想就模型相关的问题进行一些提问：
①在这个项目里使用的efficient-b2模型，我下载了源生的B2模型并使用了 onnx-simplifier 进行优化，俩者进行比对，我发现整体结构上2者一致，但是该项目中的b2模型去掉了Pad层与BatchNormalization层，并且在我自己的一些实验中特征提取的能力（尤其是单一目标的情况下）要优于源生优化的模型，请问这是有什么原理嘛？
②onnx在遇到这个项目之前只是了解但没有实战过，所以不是很清楚，而且即便是在网上查阅资料也经常找不到所需的信息，所以遇到了一些问题：1.我使用了onnxruntime的gpu版本，但速度不理想，其中会报出没有cuda kernel我也不明白什么意思 2.如何对onnx模型进行修改，比如把batch从1改成100，我现在只能从一开始就下载一个100batch的模型然后再优化 3.请问该项目中的b2模型是如何去掉指定层的，再去掉指定层后有没有进一步做再训练？
如果方便的话，我们可以加QQ或者WX进行讨论，谢谢了。

**Comment by Sg4Dylan** [comment]
1.1 onnx-simplifier 的作用是通过等价替换简化模型结构提升推理性能，但简化前后提取的特征向量应该是一致的。如果遇到了两者提取特征向量不一致的问题，请先切换到 CPU 后端查看结果。顺便建议在导出模型时将模型转换到 CPU 后端导出。  

2.1 ONNXRuntime 后端的执行效率取决于任务的类型，对于 EfficientNet-B2 级别的模型使用 CPU 推理通常更快（batch_size=1 且 启用 SIMD 指令）。报错请移步其官方项目。  

2.2 修改模型通常在导出前进行。可以参考相关文档使导出模型使用其他的固定输入尺寸，或完全支持动态输入尺寸（对于全卷积网络），但似乎 onnx-simplifier 不支持动态尺寸调整。  

2.3 本项目中附带的预训练模型除使用 onnx-simplifier 简化模型未额外修改网络结构。通常修改网络后要执行 finetune 以维持精度。
