### ISSUE TITLE
请问会支持batch推理或tensorRT加速的方式建索引吗？

### ISSUE THREAD

**Issue by tomjerrygithub** [Sg4Dylan/EfficientIR#3]
请问会支持batch推理或tensorRT加速的方式建索引吗？

**Comment by Sg4Dylan** [comment]
关于 Batch 方式建立索引的问题不是没有考虑过的，大概有这么些问题：
因为 GPU 性能参差不齐（推理效能、显存大小），所以要做 Batch 就有必要动态输入尺寸。
然而做动态输入尺寸就意味着当前使用的模型优化方法无法使用，会导致推理效能下降。
退一步使用多个固定输入尺寸模型也可以，但同时意味着程序打包体积倍增。

能确实解决上述问题的时候，Batch 推理建立索引特性就会加入的。

至于 TensorRT 加速，通常 ONNXRuntime 后端通常可以无缝替换，
你可以尝试编译安装 TensorRT ONNXRuntime，修改代码替换后端为 TensorrtExecutionProvider。
