### ISSUE TITLE
Windows 环境特定问题

### ISSUE THREAD

**Issue by lucsirotouka** [Sg4Dylan/EfficientIR#6]
首先感谢本工具作者，这种小众需求真的很难找现成实现。
在 Windows 环境下运行时，有两个环境特定的问题，希望可以进行改进。

**1. 对于 UNC 路径的搜索结果，当双击搜索结果条目时，会异常退出。**
例如：建立索引时，来源包含 \\\\10.0.0.1\images，其中一个搜索结果是 \\\\10.0.0.1\images\1.jpg，当双击搜索结果中的该条目时，程序会异常退出。

**2. 对于超长路径，建立索引时会由于超出 Windows 默认的路径最大长度，会在报异常后中断缩进创建流程退出。**
如下为日志内容：
```
删除不存在文件: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 137, in sync_index
    need_index = utils.index_target_dir(image_dir)
  File "D:\EfficientIR\utils.py", line 59, in index_target_dir
    file_size = os.path.getsize(exists_index[i])
  File "genericpath.py", line 50, in getsize
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '//10.0.0.1/data/
一级目录\\二级目录\\dir3\\四级目录1234字字5字indd\\“1234.5字字字”文件夹\\“123
4.5字字字”文件夹\\Links\\interior-design-modern-furniture-bathroom-ideas-glitte
ring-minimalist-modern-bathroom-minimalist-white-bathroom-vanity-unit-900mm-mini
malist-white-bathroom-minimalist-black-and-white-bathroom-mi.jpg'
```

不知是否可进行改进，谢谢！

_2022/06/30：由于之前对 Issue 操作不熟悉，误点 Close issue，故在此处更新关于第 2 个问题的说明：_

经过二次测试，即使在注册表中启用 LongPathsEnabled，在 Windows 10 下仍然会出现 UNC 超长路径时回报 WinError 3 系统找不到指定的路径的异常，此时可发现异常信息中包含的路径混用了 // 和 \\，猜测可能是 UNC 路径中这样撰写不合法。

变通的方法是**先将 UNC 路径映射为网络驱动器**，然后用映射的盘符建立索引，即可正常使用 LongPathsEnabled 提供的长路径支持，从而正常对图片进行索引更新操作。

**Comment by Sg4Dylan** [comment]
感谢您的反馈！

关于您提到的第一个问题已经确认存在，将在下一次更新中进行修复。
具体的修复方式是改写运行目录下 `main.py` 文件中的 `double_click_search_table` 方法：
修复前：
```python
def double_click_search_table(self, info):
    row = info.row()
    os.startfile(self.resultTable.item(row, 0).text())
```

修复后：
```python
def double_click_search_table(self, info):
    file_path = self.resultTable.item(info.row(), 0).text()
    os.startfile(os.path.normpath(file_path))
```

关于您提到的第二个问题，在相同 UNC 路径 + 超过 260 字符长度条件下并未复现成功，推测与您的系统设置相关。
可以参考这里的说明进行设置后再次尝试：https://support.cs.jhu.edu/wiki/Windows_Path_Length_Limit_Reached

谢谢。
